### PR TITLE
Only consider a root if it's a symlink

### LINKED ISSUE #106: nix-tree no longer works by default, does not contain a 'flake.nix', searching up
```
x nix run 'nixpkgs#nix-tree' -- --version
nix-tree 0.5.0
```

```
x nix run 'nixpkgs#nix-tree'
path '/home/me/.local/state/nix/profile' does not contain a 'flake.nix', searching up
error: could not find a flake.nix file
nix-tree: Received ExitFailure 1 when running
Raw command: nix path-info --json --extra-experimental-features "nix-command flakes" /home/me/.local/state/nix/profile /var/run/current-system
```

```
> nix --version
nix (Nix) 2.24.10
```

I guess this is caused by the newer nix version?

`nix-tree /var/run/current-system` still works
So I have to use `nix run 'nixpkgs#nix-tree' --  /var/run/current-system` instead now.
Somewhere between the version, the default behavior changed so now I have to pass in current-system explicitly nowadays?

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
Fixes #106

### CODE REVIEW

File: src/NixTree/Main.hs [hunk 1]
```diff
@@ -91,6 +91,17 @@ showAndFail msg = do
...
+isValidRoot :: FilePath -> IO Bool
+isValidRoot path = do
+  isExistingDirectory <- doesDirectoryExist path
+  if isExistingDirectory
+    then -- We need to check that it's a symlink (presumably to nix store),
+    -- because if it is just a directory, nix will try to interpret it as a flake.
+    -- We do doesDirectoryExist before pathIsSymbolicLink,
+    -- because the latter will fail if the path does not exist.
+      pathIsSymbolicLink path
+    else return False
```
Comment (utdemir) [inline src/NixTree/Main.hs:103]: ❤️ for the comment
